name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - master # 触发部署的分支

jobs:
  build:
    runs-on: ubuntu-latest

    # ↓ 在这里声明环境变量 DEPLOY_ENV
    env:
      DEPLOY_ENV: GH_PAGES

    steps:
      # 获取仓库代码
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true # 一定要放在 with: 下
          fetch-depth: 0 # 拉全历史，方便 gh-pages 推送

      # 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # 选择你使用的 Node.js 版本

      # 安装依赖并构建应用
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # 部署到 gh-pages 分支
          folder: out # Next.js 导出的静态文件目录
          token: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub Token 进行认证
